### ISSUE TITLE
[Meta] Identify enrollment specific needs/features

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/quartz#103]

**Comment by JavaLavaMT** [comment]
- [ ] able to simply compare plans 
- [ ] payment breakdown (month/paycheck)
- [ ] new tab for in-progress/past and completed insurance forms 
- [ ] tool-tips for vocabulary words?
- [ ] display links to links that would be relative (not 100% sure what is required)
- [ ] view and edit the current plan 
- [ ] be cool if we could show:
       1. the hospitals that are in-network
       2. deductable (maybe what they have left to reach it as well?)
- [ ] print ID cards
- [ ] change beneficiaries/dependents
- [ ] progress saveable (not sure if Quartz has increment saving)
- [ ] send a message from in the app to HR to ask a question
- [ ] signature
- [ ] uploading app after print??
- [ ] ability to wave coverage
- [ ] life event change
- [ ] review the app before submitting
